# Generated by Django 3.2.4 on 2021-06-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliveried',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='table_seat',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
