# Generated by Django 3.2.4 on 2021-06-30 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210629_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='table_seat',
        ),
        migrations.AddField(
            model_name='order',
            name='position',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='track',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
